### ISSUE TITLE
Httpx Version

### ISSUE THREAD

**Issue by Root-Time** [Rickaym/discord-ext-i18n#1]
The Package "googletrans" is not working with higher httpx Version just with 0.13.3. But other package need higher httpx Verison like Prisma. 

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
googletrans 3.1.0a0 requires httpx==0.13.3, but you have httpx 0.23.0 which is incompatible.

**Comment by Rickaym** [comment]
Hey Root-Time,

Have you tried downgrading Prisma--is it something that could work for you? 
Otherwise, I'm not sure if you can work with conflicting packages, perhaps also try using a higher version of googletrans (but they are known to be broken).

As a last resort, you can find a new translation package and use that instead of googletrans, all the necessary modification details should be in the examples.

**Comment by Root-Time** [comment]
> Hey Root-Time,
> 
> Have you tried downgrading Prisma--is it something that could work for you? Otherwise, I'm not sure if you can work with conflicting packages, perhaps also try using a higher version of googletrans (but they are known to be broken).
> 
> As a last resort, you can find a new translation package and use that instead of googletrans, all the necessary modification details should be in the examples.

Yeah i found a sulotion. I Just used a fork of yours.

**Comment by Root-Time** [comment]
> Hey Root-Time,
> 
> Have you tried downgrading Prisma--is it something that could work for you? Otherwise, I'm not sure if you can work with conflicting packages, perhaps also try using a higher version of googletrans (but they are known to be broken).
> 
> As a last resort, you can find a new translation package and use that instead of googletrans, all the necessary modification details should be in the examples.

Yeah i reviewed you Code and impleted myself with a fork from googletrans with a Higher httpx Version. But Thank you for you time.

**Comment by Rickaym** [comment]
Oh great, no problem!
